#!/usr/bin/env python3
"""AI Music Factory — Web Dashboard"""
import os
import sys
import json
import uuid
import webbrowser
import threading
from pathlib import Path

os.environ["PYTHONIOENCODING"] = "utf-8"

from flask import Flask, render_template, request, jsonify, Response, send_from_directory

from core.event_bus import event_bus
from core.job_manager import job_manager
from core.cost_tracker import cost_tracker
from core.config import get_config, save_config, get_presets, validate

app = Flask(__name__)

OUTPUT_DIR = os.getenv("PLAYLIST_OUTPUT_DIR", str(Path.home() / "music" / "AI_Playlist"))


# ─── Pages ───────────────────────────────────
@app.route("/")
def dashboard():
    return render_template("dashboard.html")


@app.route("/new")
def new_job_page():
    return render_template("new_job.html", presets=get_presets())


@app.route("/job/<job_id>")
def job_detail_page(job_id):
    return render_template("job_detail.html", job_id=job_id)


@app.route("/settings")
def settings_page():
    return render_template("settings.html")


@app.route("/browse")
def browser_page():
    return render_template("browser.html")


@app.route("/brands")
def brands_page():
    return render_template("brands.html")


# ─── API ─────────────────────────────────────
@app.route("/api/jobs", methods=["GET"])
def api_list_jobs():
    return jsonify(job_manager.list_jobs())


@app.route("/api/jobs", methods=["POST"])
def api_create_job():
    config = request.json
    if not config:
        return jsonify({"error": "No config"}), 400
    config.setdefault("output_dir", OUTPUT_DIR)
    job = job_manager.create_job(config)
    return jsonify({"job_id": job.id, "status": "created"})


@app.route("/api/jobs/<job_id>")
def api_get_job(job_id):
    job = job_manager.get_job(job_id)
    if not job:
        return jsonify({"error": "Not found"}), 404
    return jsonify(job.to_dict())


@app.route("/api/jobs/<job_id>/cancel", methods=["POST"])
def api_cancel_job(job_id):
    job_manager.cancel_job(job_id)
    return jsonify({"status": "cancelled"})


@app.route("/api/jobs/<job_id>", methods=["DELETE"])
def api_delete_job(job_id):
    if job_manager.delete_job(job_id):
        return jsonify({"status": "deleted"})
    return jsonify({"error": "Not found"}), 404


@app.route("/api/jobs/<job_id>/retry", methods=["POST"])
def api_retry_track(job_id):
    data = request.json or {}
    track_number = data.get("track_number")
    if not track_number:
        return jsonify({"error": "track_number required"}), 400
    if job_manager.retry_track(job_id, track_number):
        return jsonify({"status": "retrying"})
    return jsonify({"error": "Cannot retry"}), 400


@app.route("/api/disk-stats")
def api_disk_stats():
    return jsonify(job_manager.get_disk_stats())


BRAND_PROFILES_FILE = Path(__file__).parent / "brand_profiles.json"


@app.route("/api/jobs/<job_id>/timeline")
def api_job_timeline(job_id):
    """작업의 트랙들로 YouTube 타임라인 자동 생성"""
    job = job_manager.get_job(job_id)
    if not job:
        return jsonify({"error": "Not found"}), 404

    d = job.to_dict()
    tracks = [t for t in d.get("tracks", []) if t.get("status") == "success" and t.get("duration_sec")]

    if not tracks:
        return jsonify({"error": "No completed tracks"}), 400

    # 타임스탬프 계산
    concept = d.get("concepts", [{}])[0]
    concept_name = concept.get("concept_name", "AI Music Playlist")
    timeline_lines = []
    current_sec = 0

    for t in sorted(tracks, key=lambda x: x.get("track_number", 0)):
        h = int(current_sec // 3600)
        m = int((current_sec % 3600) // 60)
        s = int(current_sec % 60)
        if h > 0:
            ts = f"{h}:{m:02d}:{s:02d}"
        else:
            ts = f"{m}:{s:02d}"
        title = t.get("title_ko", t.get("title_en", f"Track {t.get('track_number', '?')}"))
        timeline_lines.append({
            "timestamp": ts,
            "title": title,
            "track_number": t.get("track_number", 0),
            "duration_sec": t.get("duration_sec", 0),
            "start_sec": current_sec,
        })
        current_sec += t.get("duration_sec", 0)

    # 총 재생시간
    total_h = int(current_sec // 3600)
    total_m = int((current_sec % 3600) // 60)
    total_s = int(current_sec % 60)
    total_str = f"{total_h}시간 {total_m}분" if total_h > 0 else f"{total_m}분 {total_s}초"

    # YouTube 설명용 텍스트
    yt_desc = f"🎵 {concept_name}\n"
    yt_desc += f"총 {len(tracks)}곡 · {total_str}\n\n"
    yt_desc += "📋 타임라인\n"
    for item in timeline_lines:
        yt_desc += f"{item['timestamp']} {item['title']}\n"
    yt_desc += f"\n🤖 Generated by AI Music Factory\n"

    return jsonify({
        "concept_name": concept_name,
        "total_tracks": len(tracks),
        "total_duration_sec": round(current_sec, 1),
        "total_duration_str": total_str,
        "timeline": timeline_lines,
        "youtube_description": yt_desc,
    })


@app.route("/api/browse-timeline")
def api_browse_timeline():
    """디스크 폴더에서 타임라인 생성"""
    folder = request.args.get("path", "")
    if not folder:
        return jsonify({"error": "path required"}), 400

    folder_path = Path(folder)
    if not folder_path.exists():
        return jsonify({"error": "not found"}), 404

    # _playlist_info.json 읽기
    info_file = folder_path / "_playlist_info.json"
    concept_name = folder_path.name
    tracks = []

    if info_file.exists():
        try:
            info = json.loads(info_file.read_text(encoding="utf-8"))
            concept_name = info.get("concept", {}).get("concept_name", concept_name)
            tracks = info.get("tracks", [])
        except Exception:
            pass

    # info 없으면 mp3 파일 직접 스캔
    if not tracks:
        import subprocess
        mp3s = sorted(folder_path.glob("*.mp3"))
        for i, mp3 in enumerate(mp3s):
            dur = 0
            try:
                r = subprocess.run(
                    ["ffprobe", "-v", "quiet", "-show_entries", "format=duration",
                     "-of", "csv=p=0", str(mp3)],
                    capture_output=True, text=True, timeout=10
                )
                dur = float(r.stdout.strip()) if r.stdout.strip() else 0
            except Exception:
                pass
            tracks.append({
                "track_number": i + 1,
                "title_ko": mp3.stem,
                "duration_sec": round(dur, 1),
                "filename": mp3.name,
            })

    success_tracks = [t for t in tracks if t.get("duration_sec", 0) > 0]
    if not success_tracks:
        return jsonify({"error": "No tracks with duration"}), 400

    current_sec = 0
    timeline_lines = []
    for t in sorted(success_tracks, key=lambda x: x.get("track_number", 0)):
        h = int(current_sec // 3600)
        m = int((current_sec % 3600) // 60)
        s = int(current_sec % 60)
        ts = f"{h}:{m:02d}:{s:02d}" if h > 0 else f"{m}:{s:02d}"
        title = t.get("title_ko", t.get("filename", ""))
        timeline_lines.append({
            "timestamp": ts, "title": title,
            "track_number": t.get("track_number", 0),
            "duration_sec": t.get("duration_sec", 0),
            "start_sec": current_sec,
        })
        current_sec += t.get("duration_sec", 0)

    total_h = int(current_sec // 3600)
    total_m = int((current_sec % 3600) // 60)
    total_s = int(current_sec % 60)
    total_str = f"{total_h}시간 {total_m}분" if total_h > 0 else f"{total_m}분 {total_s}초"

    yt_desc = f"🎵 {concept_name}\n"
    yt_desc += f"총 {len(success_tracks)}곡 · {total_str}\n\n"
    yt_desc += "📋 타임라인\n"
    for item in timeline_lines:
        yt_desc += f"{item['timestamp']} {item['title']}\n"
    yt_desc += f"\n🤖 Generated by AI Music Factory\n"

    return jsonify({
        "concept_name": concept_name,
        "total_tracks": len(success_tracks),
        "total_duration_sec": round(current_sec, 1),
        "total_duration_str": total_str,
        "timeline": timeline_lines,
        "youtube_description": yt_desc,
    })


@app.route("/api/brand-profiles", methods=["GET"])
def api_get_brand_profiles():
    if BRAND_PROFILES_FILE.exists():
        return jsonify(json.loads(BRAND_PROFILES_FILE.read_text(encoding="utf-8")))
    return jsonify([])


@app.route("/api/brand-profiles", methods=["POST"])
def api_save_brand_profiles():
    data = request.json
    if not data or "profiles" not in data:
        return jsonify({"error": "No profiles"}), 400
    BRAND_PROFILES_FILE.write_text(
        json.dumps(data["profiles"], ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return jsonify({"status": "saved"})


@app.route("/api/events")
def sse_stream():
    client_id = str(uuid.uuid4())

    def generate():
        event_bus.subscribe(client_id)
        try:
            yield from event_bus.listen(client_id)
        finally:
            event_bus.unsubscribe(client_id)

    return Response(
        generate(),
        mimetype="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )


@app.route("/api/cost")
def api_cost():
    return jsonify(cost_tracker.get_total())


@app.route("/api/settings", methods=["GET"])
def api_get_settings():
    cfg = get_config()
    # API 키 마스킹
    for key in ("ANTHROPIC_API_KEY", "GEMINI_API_KEY"):
        val = cfg.get(key, "")
        if len(val) > 8:
            cfg[key] = val[:4] + "..." + val[-4:]
    cfg["issues"] = validate()
    return jsonify(cfg)


@app.route("/api/settings", methods=["POST"])
def api_save_settings():
    updates = request.json
    if not updates:
        return jsonify({"error": "No data"}), 400
    save_config(updates)
    return jsonify({"status": "saved"})


@app.route("/api/presets")
def api_presets():
    return jsonify(get_presets())


@app.route("/api/recent-folders")
def api_recent_folders():
    """최근 생성된 음악 폴더 목록 (대시보드용)"""
    base = Path(OUTPUT_DIR)
    if not base.exists():
        return jsonify([])

    folders = []
    for d in sorted(base.iterdir(), reverse=True):
        if not d.is_dir() or d.name.startswith("_"):
            continue
        # 폴더 내 mp3 파일 수 + 총 크기
        mp3s = list(d.glob("*.mp3"))
        total_bytes = sum(f.stat().st_size for f in mp3s)
        if total_bytes > 1024 * 1024:
            size_str = f"{total_bytes / (1024*1024):.1f}MB"
        else:
            size_str = f"{total_bytes / 1024:.0f}KB"

        # 날짜 파싱 (폴더명 앞 8자리)
        date_str = d.name[:8] if len(d.name) >= 8 and d.name[:8].isdigit() else ""
        if date_str:
            date_str = f"{date_str[:4]}-{date_str[4:6]}-{date_str[6:8]}"

        # _playlist_info.json에서 추가 정보
        info_file = d / "_playlist_info.json"
        concept_name = d.name[9:] if len(d.name) > 9 else d.name  # 날짜 제거
        if info_file.exists():
            try:
                info = json.loads(info_file.read_text(encoding="utf-8"))
                concept_name = info.get("concept", {}).get("concept_name", concept_name)
            except Exception:
                pass

        folders.append({
            "name": concept_name.replace("_", " "),
            "path": str(d),
            "track_count": len(mp3s),
            "total_size": size_str,
            "date": date_str,
        })

    return jsonify(folders[:20])


@app.route("/api/open-folder")
def api_open_folder():
    """탐색기로 폴더 열기"""
    folder = request.args.get("path", OUTPUT_DIR)
    folder_path = Path(folder)
    if folder_path.exists():
        import subprocess as sp
        sp.Popen(["explorer", str(folder_path)])
        return jsonify({"status": "opened"})
    return jsonify({"error": "not found"}), 404


@app.route("/api/browse")
def api_browse():
    base = Path(request.args.get("path", OUTPUT_DIR))
    if not base.exists():
        return jsonify({"dirs": [], "files": []})

    dirs = sorted([d.name for d in base.iterdir() if d.is_dir()], reverse=True)
    files = []
    for f in sorted(base.iterdir()):
        if f.is_file() and f.suffix in (".mp3", ".wav", ".json"):
            files.append({
                "name": f.name,
                "size_kb": round(f.stat().st_size / 1024),
                "type": f.suffix,
            })
    return jsonify({"path": str(base), "dirs": dirs, "files": files})


@app.route("/audio/<path:filepath>")
def serve_audio(filepath):
    full = Path(filepath)
    if full.exists() and full.suffix in (".mp3", ".wav"):
        return send_from_directory(str(full.parent), full.name)
    return "Not found", 404


if __name__ == "__main__":
    port = int(os.getenv("PORT", 5000))
    print(f"\n  AI Music Factory Dashboard")
    print(f"  http://localhost:{port}\n")
    threading.Timer(1.5, lambda: webbrowser.open(f"http://localhost:{port}")).start()
    app.run(host="0.0.0.0", port=port, debug=False, threaded=True)
